version: "3.4"

services:
  app:
    build:
      dockerfile: development.Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 8080:8080

  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical_clinic
    ports:
      - "5432:5432"