// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	GooseDBVersion   string
	HealthInsurances string
	Users            string
}{
	GooseDBVersion:   "goose_db_version",
	HealthInsurances: "health_insurances",
	Users:            "users",
}
