// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// HealthInsurance is an object representing the database table.
type HealthInsurance struct {
	ID        int       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name      string    `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedAt null.Time `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	UpdatedAt null.Time `boil:"updated_at" json:"updated_at,omitempty" toml:"updated_at" yaml:"updated_at,omitempty"`

	R *healthInsuranceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L healthInsuranceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var HealthInsuranceColumns = struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	Name:      "name",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var HealthInsuranceTableColumns = struct {
	ID        string
	Name      string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "health_insurances.id",
	Name:      "health_insurances.name",
	CreatedAt: "health_insurances.created_at",
	UpdatedAt: "health_insurances.updated_at",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod   { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var HealthInsuranceWhere = struct {
	ID        whereHelperint
	Name      whereHelperstring
	CreatedAt whereHelpernull_Time
	UpdatedAt whereHelpernull_Time
}{
	ID:        whereHelperint{field: "\"health_insurances\".\"id\""},
	Name:      whereHelperstring{field: "\"health_insurances\".\"name\""},
	CreatedAt: whereHelpernull_Time{field: "\"health_insurances\".\"created_at\""},
	UpdatedAt: whereHelpernull_Time{field: "\"health_insurances\".\"updated_at\""},
}

// HealthInsuranceRels is where relationship names are stored.
var HealthInsuranceRels = struct {
}{}

// healthInsuranceR is where relationships are stored.
type healthInsuranceR struct {
}

// NewStruct creates a new relationship struct
func (*healthInsuranceR) NewStruct() *healthInsuranceR {
	return &healthInsuranceR{}
}

// healthInsuranceL is where Load methods for each relationship are stored.
type healthInsuranceL struct{}

var (
	healthInsuranceAllColumns            = []string{"id", "name", "created_at", "updated_at"}
	healthInsuranceColumnsWithoutDefault = []string{"name"}
	healthInsuranceColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	healthInsurancePrimaryKeyColumns     = []string{"id"}
	healthInsuranceGeneratedColumns      = []string{}
)

type (
	// HealthInsuranceSlice is an alias for a slice of pointers to HealthInsurance.
	// This should almost always be used instead of []HealthInsurance.
	HealthInsuranceSlice []*HealthInsurance
	// HealthInsuranceHook is the signature for custom HealthInsurance hook methods
	HealthInsuranceHook func(context.Context, boil.ContextExecutor, *HealthInsurance) error

	healthInsuranceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	healthInsuranceType                 = reflect.TypeOf(&HealthInsurance{})
	healthInsuranceMapping              = queries.MakeStructMapping(healthInsuranceType)
	healthInsurancePrimaryKeyMapping, _ = queries.BindMapping(healthInsuranceType, healthInsuranceMapping, healthInsurancePrimaryKeyColumns)
	healthInsuranceInsertCacheMut       sync.RWMutex
	healthInsuranceInsertCache          = make(map[string]insertCache)
	healthInsuranceUpdateCacheMut       sync.RWMutex
	healthInsuranceUpdateCache          = make(map[string]updateCache)
	healthInsuranceUpsertCacheMut       sync.RWMutex
	healthInsuranceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var healthInsuranceAfterSelectMu sync.Mutex
var healthInsuranceAfterSelectHooks []HealthInsuranceHook

var healthInsuranceBeforeInsertMu sync.Mutex
var healthInsuranceBeforeInsertHooks []HealthInsuranceHook
var healthInsuranceAfterInsertMu sync.Mutex
var healthInsuranceAfterInsertHooks []HealthInsuranceHook

var healthInsuranceBeforeUpdateMu sync.Mutex
var healthInsuranceBeforeUpdateHooks []HealthInsuranceHook
var healthInsuranceAfterUpdateMu sync.Mutex
var healthInsuranceAfterUpdateHooks []HealthInsuranceHook

var healthInsuranceBeforeDeleteMu sync.Mutex
var healthInsuranceBeforeDeleteHooks []HealthInsuranceHook
var healthInsuranceAfterDeleteMu sync.Mutex
var healthInsuranceAfterDeleteHooks []HealthInsuranceHook

var healthInsuranceBeforeUpsertMu sync.Mutex
var healthInsuranceBeforeUpsertHooks []HealthInsuranceHook
var healthInsuranceAfterUpsertMu sync.Mutex
var healthInsuranceAfterUpsertHooks []HealthInsuranceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *HealthInsurance) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *HealthInsurance) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *HealthInsurance) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *HealthInsurance) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *HealthInsurance) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *HealthInsurance) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *HealthInsurance) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *HealthInsurance) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *HealthInsurance) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range healthInsuranceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddHealthInsuranceHook registers your hook function for all future operations.
func AddHealthInsuranceHook(hookPoint boil.HookPoint, healthInsuranceHook HealthInsuranceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		healthInsuranceAfterSelectMu.Lock()
		healthInsuranceAfterSelectHooks = append(healthInsuranceAfterSelectHooks, healthInsuranceHook)
		healthInsuranceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		healthInsuranceBeforeInsertMu.Lock()
		healthInsuranceBeforeInsertHooks = append(healthInsuranceBeforeInsertHooks, healthInsuranceHook)
		healthInsuranceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		healthInsuranceAfterInsertMu.Lock()
		healthInsuranceAfterInsertHooks = append(healthInsuranceAfterInsertHooks, healthInsuranceHook)
		healthInsuranceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		healthInsuranceBeforeUpdateMu.Lock()
		healthInsuranceBeforeUpdateHooks = append(healthInsuranceBeforeUpdateHooks, healthInsuranceHook)
		healthInsuranceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		healthInsuranceAfterUpdateMu.Lock()
		healthInsuranceAfterUpdateHooks = append(healthInsuranceAfterUpdateHooks, healthInsuranceHook)
		healthInsuranceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		healthInsuranceBeforeDeleteMu.Lock()
		healthInsuranceBeforeDeleteHooks = append(healthInsuranceBeforeDeleteHooks, healthInsuranceHook)
		healthInsuranceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		healthInsuranceAfterDeleteMu.Lock()
		healthInsuranceAfterDeleteHooks = append(healthInsuranceAfterDeleteHooks, healthInsuranceHook)
		healthInsuranceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		healthInsuranceBeforeUpsertMu.Lock()
		healthInsuranceBeforeUpsertHooks = append(healthInsuranceBeforeUpsertHooks, healthInsuranceHook)
		healthInsuranceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		healthInsuranceAfterUpsertMu.Lock()
		healthInsuranceAfterUpsertHooks = append(healthInsuranceAfterUpsertHooks, healthInsuranceHook)
		healthInsuranceAfterUpsertMu.Unlock()
	}
}

// One returns a single healthInsurance record from the query.
func (q healthInsuranceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*HealthInsurance, error) {
	o := &HealthInsurance{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for health_insurances")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all HealthInsurance records from the query.
func (q healthInsuranceQuery) All(ctx context.Context, exec boil.ContextExecutor) (HealthInsuranceSlice, error) {
	var o []*HealthInsurance

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to HealthInsurance slice")
	}

	if len(healthInsuranceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all HealthInsurance records in the query.
func (q healthInsuranceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count health_insurances rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q healthInsuranceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if health_insurances exists")
	}

	return count > 0, nil
}

// HealthInsurances retrieves all the records using an executor.
func HealthInsurances(mods ...qm.QueryMod) healthInsuranceQuery {
	mods = append(mods, qm.From("\"health_insurances\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"health_insurances\".*"})
	}

	return healthInsuranceQuery{q}
}

// FindHealthInsurance retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindHealthInsurance(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*HealthInsurance, error) {
	healthInsuranceObj := &HealthInsurance{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"health_insurances\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, healthInsuranceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from health_insurances")
	}

	if err = healthInsuranceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return healthInsuranceObj, err
	}

	return healthInsuranceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *HealthInsurance) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no health_insurances provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		if queries.MustTime(o.UpdatedAt).IsZero() {
			queries.SetScanner(&o.UpdatedAt, currTime)
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(healthInsuranceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	healthInsuranceInsertCacheMut.RLock()
	cache, cached := healthInsuranceInsertCache[key]
	healthInsuranceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			healthInsuranceAllColumns,
			healthInsuranceColumnsWithDefault,
			healthInsuranceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(healthInsuranceType, healthInsuranceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(healthInsuranceType, healthInsuranceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"health_insurances\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"health_insurances\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into health_insurances")
	}

	if !cached {
		healthInsuranceInsertCacheMut.Lock()
		healthInsuranceInsertCache[key] = cache
		healthInsuranceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the HealthInsurance.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *HealthInsurance) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	healthInsuranceUpdateCacheMut.RLock()
	cache, cached := healthInsuranceUpdateCache[key]
	healthInsuranceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			healthInsuranceAllColumns,
			healthInsurancePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update health_insurances, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"health_insurances\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, healthInsurancePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(healthInsuranceType, healthInsuranceMapping, append(wl, healthInsurancePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update health_insurances row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for health_insurances")
	}

	if !cached {
		healthInsuranceUpdateCacheMut.Lock()
		healthInsuranceUpdateCache[key] = cache
		healthInsuranceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q healthInsuranceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for health_insurances")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for health_insurances")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o HealthInsuranceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), healthInsurancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"health_insurances\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, healthInsurancePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in healthInsurance slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all healthInsurance")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *HealthInsurance) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no health_insurances provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
		queries.SetScanner(&o.UpdatedAt, currTime)
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(healthInsuranceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	healthInsuranceUpsertCacheMut.RLock()
	cache, cached := healthInsuranceUpsertCache[key]
	healthInsuranceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			healthInsuranceAllColumns,
			healthInsuranceColumnsWithDefault,
			healthInsuranceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			healthInsuranceAllColumns,
			healthInsurancePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert health_insurances, could not build update column list")
		}

		ret := strmangle.SetComplement(healthInsuranceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(healthInsurancePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert health_insurances, could not build conflict column list")
			}

			conflict = make([]string, len(healthInsurancePrimaryKeyColumns))
			copy(conflict, healthInsurancePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"health_insurances\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(healthInsuranceType, healthInsuranceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(healthInsuranceType, healthInsuranceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert health_insurances")
	}

	if !cached {
		healthInsuranceUpsertCacheMut.Lock()
		healthInsuranceUpsertCache[key] = cache
		healthInsuranceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single HealthInsurance record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *HealthInsurance) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no HealthInsurance provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), healthInsurancePrimaryKeyMapping)
	sql := "DELETE FROM \"health_insurances\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from health_insurances")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for health_insurances")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q healthInsuranceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no healthInsuranceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from health_insurances")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for health_insurances")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o HealthInsuranceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(healthInsuranceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), healthInsurancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"health_insurances\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, healthInsurancePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from healthInsurance slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for health_insurances")
	}

	if len(healthInsuranceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *HealthInsurance) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindHealthInsurance(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *HealthInsuranceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := HealthInsuranceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), healthInsurancePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"health_insurances\".* FROM \"health_insurances\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, healthInsurancePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in HealthInsuranceSlice")
	}

	*o = slice

	return nil
}

// HealthInsuranceExists checks if the HealthInsurance row exists.
func HealthInsuranceExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"health_insurances\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if health_insurances exists")
	}

	return exists, nil
}

// Exists checks if the HealthInsurance row exists.
func (o *HealthInsurance) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return HealthInsuranceExists(ctx, exec, o.ID)
}
